remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Supercar Recognizer
description: An image classification API that classifies 20 different types of Supercars around the world

author:
  name: S.M. Ishtiaque Ahammed Khan